name: Liquid Auth - Android - Release

on:
  push:
    branches: [ 'main', 'develop' ]
jobs:
  build:
    permissions:
      contents: write
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew build
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install
        run: npm install --save @semantic-release/changelog @semantic-release/git @semantic-release/github
      - name: Semantic Release
        run: npx semantic-release --dry-run
